### ISSUE TITLE
Suggested changes: 

### ISSUE THREAD

**Issue by Trackrise** [Trackrise/ANrena#1]
I wish I was smart enough to code all this on my own, but I'm working on it. I HIGHLY suggest the following changes.

First off, replacing the "Drafted IDs" with the IDs that were intended for drafting:

https://netrunnerdb.com/en/set/draft

These IDs have a natural minimum deck size of 30, and infinite influence, and would provide a lot more variation that we are not used to seeing in in constructed. 

Second off, changing the deck limit in ANrena from 45 and 49 to 30 and 34.

From the official draft rules: 

Corp deck size and agenda points: 30-34 cards 14-15 points; 35-39 cards 16-17 points.
All standard Android: Netrunner rules are observed, except that games are played to 6 agenda points, instead of 7.

The whole process would be faster, from drafting to actually playing the game, and I think that'd be a great thing. 

From there, the alogrithms that send the right amount of agenda points and economy and all that could be edited for a faster draft.

(As long as the Runner is forced one Fracter, Killer, Decoder and about two econ cards, they should be good to go).
(It would be nice if the Corp wasn't forced to use 3 pointers if they're drafted those at once)

So if the runner or Corp was nearing the end of their draft without these things, THAT's when the website would feed them the minimum cards need to play a real game. 

Anyways, these are just my suggestions! I know they'd be hard to implement, but man if they could be I think it'd just be swell. And maybe they're not ALL good ideas (lord knows figuring out the perfect alorithm to give to players is tricky), but I think most of them are worth a shot.

**Comment by Imerxion** [comment]
It looks like porfyalum already implement some of these ideas, and the drafting seems to be going pretty well, but I agree that the Draft IDs would be great. With those ones, it'd be nice if you picked you ID after the draft, and leave the other two Draft options as is, I think.
