### ISSUE TITLE
Generated a Corp deck with insufficient agenda points

### ISSUE THREAD

**Issue by JoelCFC25** [Trackrise/ANrena#10]
Not sure if picking Domestic Sleeper had anything to do with this...but here's a 49 card list I just generated that only contains 19 agenda points (needs 20-21, obviously):

**Agenda (12)**
1 Efficiency Committee
1 The Future is Now
1 House of Knives
1 NAPD Contract
1 Global Food Initiative
1 Project Beale
1 Hostile Takeover
1 Chronos Project
1 Domestic Sleepers
1 Nisei MK II
1 Self-Destruct Chips
1 The Cleaners
**Ice (19)**
1 Bailiff
1 Fairchild 2.0
1 Muckraker
1 Hive
1 Lab Dog
1 Pop-up Window
1 Viktor 1.0
1 Viper
1 Wall of Thorns
1 Wotan
1 Shadow
1 Fenris
1 Quicksand
1 Resistor
1 Negotiator
1 Snowflake
1 Ichi 2.0
1 Data Raven
1 Enigma
**Asset (8)**
1 Commercial Bankers Group
1 Launch Campaign
1 Reversed Accounts
1 PAD Campaign
1 Snare!
1 Corporate Town
1 Mental Health Clinic
1 Shi.Kyū
**Operation (7)**
3 Hedge Fund
2 Blue Level Clearance
1 Enhanced Login Protocol
1 Interns
**Upgrade (3)**
1 Caprice Nisei
1 Cyberdex Virus Suite
1 Corporate Troubleshooter

**Comment by porfyalum** [comment]
It seems domestic sleepers messed up with the agenda algorith. I'll look into it asap.

**Comment by porfyalum** [comment]
I tried to test various fixes for this and all were either way to chaotic or caused weird scenarios, until a friend suggested just removing the 0 point agendas from the agenda card pool and placing them on the regular corp side pool. After a few tries, this seems much better while deckbuilding (at least for me) and it solves the issue.  Leaving the issue open for discusion on how you feel with this change.

**Comment by JoelCFC25** [comment]
I don't have a strong feeling on it--it sounds plenty sensible and if it's easier, seems like that's the way to go. Not like I have a strong affinity for Domestic Sleepers...I think I only grabbed it because I had already taken Corporate Town. :)
