### ISSUE TITLE
Use Faction Draft IDs and Tilt Card Pool

### ISSUE THREAD

**Issue by gumOnShoe** [Trackrise/ANrena#4]
Using the rarity distribution settings to adjust the arena to shift towards the faction you've chosen could introduce some differentiation into decks while preserving the "randomness"; also, narrowing the decks to 30 & 34 card decks will allow for a speedier experience and the smaller card pool may not be felt as strongly.

That, or allowing you to pick the faction draft ID at the end of drafting as the last step.

From: reddit

**Comment by porfyalum** [comment]
Updated so that you pick the faction draft Id at the end of the draft.
